// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aexuttvuhlivabqktzez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFleHV0dHZ1aGxpdmFicWt0emV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3OTg3NDIsImV4cCI6MjA2NTM3NDc0Mn0.pdQY0wtCd-qnyBSwGGKe4tAREGLD0pxsLuwRQfno5T4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);